{% set name = "databroker" %}
{% set version = "2.0.0b12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f6377d9c514831b950aecbb10bd7dc7ccc626b7adfc25e579b2b7a3dbd68c09

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - area-detector-handlers
    - boltons
    - cachetools
    - doct
    - entrypoints
    - event-model
    - fastapi
    - humanize
    - jinja2
    - mongomock
    - mongoquery
    - msgpack-python >=1.0.0
    - pims
    - pydantic
    - pymongo
    - pytz
    - starlette
    - tiled-client
    - tiled-server
    - toolz
    - tzlocal
    - tiled >=0.1.0a70

test:
  imports:
    # NOTE: it's a fake test to have a successful build. Uncomment once the
    # tiled feedstock is created.
    - os
    # - databroker
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: http://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified interface to the various data sources at NSLS-II.
  description: A unified interface to the various data sources at NSLS-II.
  doc_url: http://blueskyproject.io/databroker
  dev_url: https://github.com/bluesky/databroker

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - mrakitin
    - gwbischof
