{% set name = "databroker" %}
{% set version = "2.0.0b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ac0def32450789bb6282126c737b6ee2eda00fdf68f270c5d79ebfd4a05b504

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - area-detector-handlers
    - bluesky-live >=0.0.6
    - boltons
    - cachetools
    - dask
    - doct
    - entrypoints
    - event-model >=1.14.0
    - fastapi
    - humanize
    - intake >=0.5.5,<=0.6.4
    - jinja2
    - jsonschema
    - mongomock
    - mongoquery
    - msgpack-numpy
    - msgpack-python
    - numpy
    - pandas
    - pims
    - pydantic
    - pymongo
    - pytz
    - pyyaml
    - requests
    - six
    - starlette
    - suitcase-mongo
    - suitcase-msgpack
    - tifffile !=2019.7.26.2
    # TODO: uncomment once
    # https://github.com/conda-forge/staged-recipes/pull/18601 is merged and
    # all the tiled* packages are on conda-forge (uploaded and indexed):
    # - tiled >=0.1.0a60
    - toolz
    - tzlocal
    - xarray
    - zarr

test:
  imports:
    # NOTE: it's a fake test to have a successful build. Uncomment once the
    # tiled feedstock is created.
    - os
    # - databroker
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: http://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified interface to the various data sources at NSLS-II.
  description: A unified interface to the various data sources at NSLS-II.
  doc_url: http://blueskyproject.io/databroker
  dev_url: https://github.com/bluesky/databroker

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - mrakitin
    - gwbischof
