{% set name = "databroker" %}
{% set version = "2.0.0b29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4f74ee96f56b0693e3cd4627a3d7045ad6e53f61bcb06f13af6aacf64021900d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - area-detector-handlers
    - boltons
    - cachetools
    - doct
    - entrypoints
    - event-model
    - fastapi
    - humanize
    - jinja2
    - jsonschema
    - mongomock
    - mongoquery
    - msgpack-python >=1.0.0
    - orjson
    - pims
    - pydantic
    - pymongo
    - pytz
    - starlette
    - tiled >=0.1.0a106
    - tiled-client
    - tiled-server
    - toolz
    - tzlocal

test:
  imports:
    - databroker
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified interface to the various data sources at NSLS-II.
  description: A unified interface to the various data sources at NSLS-II.
  doc_url: http://blueskyproject.io/databroker
  dev_url: https://github.com/bluesky/databroker

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - mrakitin
    - gwbischof
