{% set name = "databroker" %}
{% set version = "2.0.0b52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6f29abf7e90af5894cfb300ca5c1e842ff057041fb0599f924216a470407e0c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - area-detector-handlers
    - boltons
    - cachetools
    - doct
    - entrypoints
    - event-model
    - fastapi
    - humanize
    - jinja2
    - jsonschema
    - mongomock
    - mongoquery
    - msgpack-python >=1.0.0
    - orjson
    - pims
    - pydantic
    - pymongo
    - pytz
    - starlette
    - suitcase-mongo >=0.6.0
    - tiled >=0.1.0b13
    - tiled-client
    - tiled-server
    - toolz
    - tzlocal

test:
  imports:
    - databroker
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified interface to the various data sources at NSLS-II.
  description: A unified interface to the various data sources at NSLS-II.
  doc_url: http://blueskyproject.io/databroker
  dev_url: https://github.com/bluesky/databroker

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - mrakitin
    - gwbischof
