{% set name = "databroker" %}
{% set version = "2.0.0b59" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e1353e0138f7f1a492715acf00092f9137816da3fd1520ba9a1301148f3698f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - area-detector-handlers
    - bluesky-tiled-plugins
    - boltons
    - cachetools
    - doct
    - entrypoints
    - event-model
    - fastapi
    - glue-core
    - humanize
    - jinja2
    - jsonschema
    - mongomock
    - mongoquery
    - msgpack-python >=1.0.0
    - orjson
    - pims
    - pydantic
    - pymongo
    - pytz
    - requests
    - starlette
    - suitcase-mongo >=0.6.0
    - tiled >=0.1.0b20
    - tiled-client
    - tiled-server
    - toolz
    - tzlocal

test:
  imports:
    - databroker
    - databroker.assets
    - databroker.assets.base_registry
    - databroker.assets.column_hdf5
    - databroker.assets.core
    - databroker.assets.file_writers
    - databroker.assets.handlers
    - databroker.assets.handlers_base
    - databroker.assets.mongo
    - databroker.assets.mongo_core
    - databroker.assets.path_only_handlers
    - databroker.assets.readers
    - databroker.assets.readers.spe
    - databroker.assets.sqlite
    - databroker.assets.utils
    - databroker.broker
    - databroker.cli
    - databroker.client
    - databroker.databroker
    - databroker.document
    - databroker.eventsource
    - databroker.eventsource.archiver
    - databroker.eventsource.shim
    - databroker.glue
    - databroker.headersource
    - databroker.headersource.base
    - databroker.headersource.core
    - databroker.headersource.hdf5
    - databroker.headersource.mongo
    - databroker.headersource.mongo_core
    - databroker.headersource.mongoquery
    - databroker.headersource.shim
    - databroker.headersource.sqlite
    # - databroker.in_memory  # NOTE: uses 'databroker.core', need to fix in the codebase.
    - databroker.mongo_normalized
    # - databroker.pims_readers  # NOTE: failure with importing 'databroker.databroker'.
    - databroker.pivot
    - databroker.projector
    - databroker.queries
    - databroker.query_impl
    - databroker.replay
    - databroker.replay.replay_script
    - databroker.server
    - databroker.shape_fixer
    # - databroker.tutorial_utils  # NOTE: requires 'databroker_pack'.
    - databroker.utils
    - databroker.v0
    - databroker.v1
    - databroker.v2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified interface to the various data sources at NSLS-II.
  description: A unified interface to the various data sources at NSLS-II.
  doc_url: http://blueskyproject.io/databroker
  dev_url: https://github.com/bluesky/databroker

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - mrakitin
    - gwbischof
